---
abstract: 'client/server UDP handles for AnyEvent'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  IO::Socket::INET: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Handle-UDP
requires:
  AnyEvent: 0
  AnyEvent::Socket: 0
  AnyEvent::Util: 0
  Carp: 0
  Const::Fast: 0
  Errno: 0
  Moo: 0
  Scalar::Util: 0
  Socket: 0
  Symbol: 0
  namespace::clean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=AnyEvent-Handle-UDP
  repository: git://github.com/Leont/anyevent-handle-udp.git
version: 0.033
