---
abstract: 'client/server UDP handles for AnyEvent'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IO::Socket::INET: 0
  IPC::Open3: 0
  Test::Fatal: 0
  Test::More: 0.89
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Handle-UDP
provides:
  AnyEvent::Handle::UDP:
    file: lib/AnyEvent/Handle/UDP.pm
    version: 0.043
recommends:
  Sub::Name: 0
requires:
  AnyEvent: 0
  AnyEvent::Socket: 0
  AnyEvent::Util: 0
  Carp: 0
  Moo: 1.001000
  Scalar::Util: 0
  Socket: 0
  Symbol: 0
  namespace::clean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=AnyEvent-Handle-UDP
  repository: git://github.com/Leont/anyevent-handle-udp.git
version: 0.043
